[package]
name = "proxy-server"
version = "0.1.0"
edition = "2021"
description = "Low level proxy server"
authors = ["Sergei Kol'miller <uyem.ru@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["http", "proxy", "tcp"]
categories = ["network-programming"]
repository = "https://github.com/kolserdav/proxy-server"
include = ["README.md", "LICENSE", "Cargo.toml", "/src/*.rs", "src/**/*.rs"]
rust-version = "1.67"

[lib]
name = "proxy_server"

[dependencies]
regex = "1.7.1"
